require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - db/**/*
    - spec/**/*
    - public/**/*
    - vendor/bundle/**/*
    - bin/**/*
    - config/initializers/rswag_ui.rb
    - config/initializers/rswag_api.rb

Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/ModuleLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
Style/ClassAndModuleChildren:
  Enabled: false